import type { AppSpecification } from '../types/schema';

/**
 * ------------------------------------------------------------------
 * THE APP MANIFEST (The "Brain")
 * ------------------------------------------------------------------
 * This file is the Single Source of Truth for the application's
 * domain logic. It defines the signals (data), entities (things),
 * and global configuration.
 * * In the "App Builder" workflow, this file is programmatically 
 * generated by the AI Assistant.
 */

export const appManifest: AppSpecification = {
  meta: {
    name: "My Ramme App",
    version: "0.1.0",
    description: "A prototype application generated by Ramme.",
    author: "Ramme User",
    createdAt: new Date().toISOString(),
  },

  // The Data Layer
  domain: {
    // 1. Signals: The raw data points (Sensors, Statuses, Commands)
    signals: [
      // Example placeholder:
      // {
      //   id: 'temp_01',
      //   label: 'Living Room Temp',
      //   kind: 'sensor',
      //   source: 'mock',
      //   unit: '°C',
      //   defaultValue: 22
      // }
    ],

    // 2. Entities: The logical groupings (Devices, Rooms, Systems)
    entities: [
      // Example placeholder:
      // {
      //   id: 'dev_thermostat',
      //   name: 'Smart Thermostat',
      //   type: 'device',
      //   signals: ['temp_01']
      // }
    ],
  },

  // Global Config
  config: {
    theme: 'system',
    mockMode: true, // Default to "Mock Mode" for instant prototyping
  },
};